# Generated by Django 3.0.5 on 2024-07-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emb', '0005_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
