# Generated by Django 3.0.5 on 2024-10-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emb', '0007_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
