# Generated by Django 3.0.5 on 2024-10-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emb', '0008_remove_customer_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=100)),
                ('placement', models.CharField(max_length=100)),
                ('garment', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('mail_id', models.EmailField(max_length=254)),
                ('confirm_mail_id', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=15)),
            ],
        ),
    ]
